//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_drink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beverage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Beverage()
        {
            this.Order_Detail = new HashSet<Order_Detail>();
        }
    
        public int Id_beverage { get; set; }
        public string Name_beverage { get; set; }
        public Nullable<int> Typeofbeverage_id { get; set; }
        public Nullable<double> Price { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Manufacturing_date { get; set; }
        public Nullable<System.DateTime> Expiry_date { get; set; }
        public System.DateTime Date_in { get; set; }
        public Nullable<System.DateTime> Date_out { get; set; }
        public Nullable<int> Total_input { get; set; }
        public Nullable<int> Inventory { get; set; }
    
        public virtual TypeOfBeverage TypeOfBeverage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Detail> Order_Detail { get; set; }
    }
}
