//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_drink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int Id_orderdetail { get; set; }
        public Nullable<int> Beverage_id { get; set; }
        public Nullable<int> Order_id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Num { get; set; }
        public Nullable<double> Total_money { get; set; }
        public string Note { get; set; }
    
        public virtual Beverage Beverage { get; set; }
        public virtual Order Order { get; set; }
    }
}
