//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_drink
{
    using manager_drink.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
       public Order_Detail()
        {
            //this.
        }

        private int _Id_orderdetail;
        public int Id_orderdetail { get => _Id_orderdetail; set { _Id_orderdetail = value; OnPropertyChanged(); } }

        private double? _Price;
        public double? Price { get => _Price; set { _Price = value; OnPropertyChanged(); } }

        Nullable<int> _Order_id;
        public Nullable<int> Order_id { get => _Order_id; set { _Order_id = value; OnPropertyChanged(); } }

        Nullable<int> _Beverage_id;
        public Nullable<int> Beverage_id { get => _Beverage_id; set { _Beverage_id = value; OnPropertyChanged(); } }

        Nullable<double> _Total_money;
        public Nullable<double> Total_money { get => _Total_money; set { _Total_money = value; OnPropertyChanged(); } }

        Nullable<int> _Num;
        public Nullable<int> Num { get => _Num; set { _Num = value; OnPropertyChanged(); } }

        private string _Note;
        public string Note { get => _Note; set { _Note = value; OnPropertyChanged(); } }
      
        public virtual Beverage Beverage { get; set; }
        public virtual Order Order { get; set; }
    }
}
