//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace manager_drink
{
    using manager_drink.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfBeverage: BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeOfBeverage()
        {
            this.Beverages = new HashSet<Beverage>();
        }

        private string _Name_TypeOfBeverage;
        public string Name_TypeOfBeverage { get => _Name_TypeOfBeverage; set { _Name_TypeOfBeverage = value; OnPropertyChanged(); } }

        private string _Image;
        public string Image { get => _Image; set { _Image = value; OnPropertyChanged(); } }

        private int _Id_TypeOfBeverage;
        public int Id_TypeOfBeverage { get => _Id_TypeOfBeverage; set { _Id_TypeOfBeverage = value; OnPropertyChanged(); } }

        private DateTime? _Created_at;
        public DateTime? Created_at { get => _Created_at; set { _Created_at = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beverage> Beverages { get; set; }
    }
}
